spring:
  application:
    name: event-management
  jpa.hibernate:
      ddl-auto: create-drop
      show-sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode:  never
      continue-on-error: false
      data-locations: classpath:demo_data.sql
      schema-locations: classpath:schema.sql

springdoc:
  swagger-ui:
    url: /openapi.yaml
server:
  port: 8080
  servlet:
    context-path: /

security:
  jwt:
    secret: 0JzQsNC80LAg0LzRi9C70LAg0YDQsNC80YMs0LAg0JrQsNGA0Lsg0YMg0JrQu9Cw0YDRiyDRg9C60YDQsNC7INC60L7RgNCw0LvRiw==
    access: 3600000
