spring:
  application:
    name: event-management
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: mysecretpassword

springdoc:
  swagger-ui:
    url: /openapi.yaml
