spring:
  application:
    name: event-management
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always
#      continue-on-error: false
#      data-locations: classpath:demo_data.sql

springdoc:
  swagger-ui:
    url: /openapi.yaml
server:
  port: 8080
  servlet:
    context-path: /
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


