spring:
  application:
    name: event-management
  jpa.hibernate:
      ddl-auto: validate
      show-sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode:  always
      continue-on-error: false
      schema-locations: classpath:schema.sql
      data-locations: classpath:demo_data.sql


springdoc:
  swagger-ui:
    url: /openapi.yaml
server:
  port: 8081
  servlet:
    context-path: /

security:
  jwt:
    secret: 0JzQsNC80LAg0LzRi9C70LAg0YDQsNC80YMs0LAg0JrQsNGA0Lsg0YMg0JrQu9Cw0YDRiyDRg9C60YDQsNC7INC60L7RgNCw0LvRiw==
    access: 3600000
